# Change the cooldown when enabling/disabling PvP (seconds). Set to 0 to disable.
enable-cooldown: 5
disable-cooldown: 0

# Respawn location
respawn:
  enabled: true # Should the plugin teleport a player when they die?
  use-world-spawn: true # Overrides x, y, z, yaw, pitch
  x: 0
  y: 100
  z: 0
  yaw: 0
  pitch: 0

# How much health is regained on kill, this is in HP, not hearts. Set to -1 to disable
health-on-kill: 4
health-gained-message: '&aYou killed %killed% and gained +%extra% health!'

disabled-worlds:
  - world_nopvp

# --------------------------------------------------
# Messages
# --------------------------------------------------

lang:
  pvp-enabled: '&6&l>&r&a PvP enabled!'
  pvp-enabling: '&aPvP enabling in %time% second(s).'
  pvp-disabled: '&6&l>&r&c PvP disabled!'
  pvp-disabling: '&cPvP disabling in %time% second(s).'
  reloaded: '&aSuccessfully reloaded the HubPvP config!'
  killed: '&4%killer% &chas killed you.'
  killed-other: '&eYou have killed &6%killed%&e!'
  disabled-in-world: "&cYou may not use this in this world!"
